name: library_app
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.17.5 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.23.0
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  bloc: ^8.0.3
  auto_size_text: ^3.0.0
  flutter_bloc: ^8.0.1
  fluttericon: ^2.0.0
  device_preview: ^1.1.0
  flutter_rating_bar: ^4.0.1
  dotted_border: ^2.0.0+2
  textfield_tags: ^2.0.1
  flutter_tags: "^1.0.0-nullsafety.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.9

flutter_native_splash:
  color: "#009688"
  image : images/book.png
  color_dark: "#121212"
  image_dark: images/book.png

  android_12:
    image : images/book.png
    icon_background_color: "#009688"
    image_dark: images/book.png
    icon_background_color_dark: "#121212"

  web: false

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

    # To add assets to your application, add an assets section, like this:
  assets:
      - images/


  # To add assets to your application, add an assets section, like this:
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Poppins
       fonts:
         - asset: fonts/Poppins-Bold.otf
         - asset: fonts/Poppins-Regular.otf
         - asset: fonts/Poppins-Light.otf
         - asset: fonts/Poppins-Medium.otf
         - asset: fonts/Poppins-SemiBold.otf
           weight: 600
     - family: Raleway
       fonts:
         - asset: fonts/Raleway-Bold.ttf
         - asset: fonts/Raleway-Regular.ttf

  #     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages